// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5a54hkzvPiIck4MPijeSKWS2pUB6Tiwc',
    appId: '1:925958524071:web:26146c54016a77efbcdf82',
    messagingSenderId: '925958524071',
    projectId: 'michi-kahoot',
    authDomain: 'michi-kahoot.firebaseapp.com',
    storageBucket: 'michi-kahoot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1Eqdyk78G6FAYGxS59cQ8AuXy37ZmZs',
    appId: '1:925958524071:android:bb29ccd8e8dd22cebcdf82',
    messagingSenderId: '925958524071',
    projectId: 'michi-kahoot',
    storageBucket: 'michi-kahoot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGmqyZJYug6Ggxt6L2wTfuXCH1Z-nP-9M',
    appId: '1:925958524071:ios:3feab35147ed51ccbcdf82',
    messagingSenderId: '925958524071',
    projectId: 'michi-kahoot',
    storageBucket: 'michi-kahoot.firebasestorage.app',
    iosBundleId: 'com.example.miniKahootTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGmqyZJYug6Ggxt6L2wTfuXCH1Z-nP-9M',
    appId: '1:925958524071:ios:3feab35147ed51ccbcdf82',
    messagingSenderId: '925958524071',
    projectId: 'michi-kahoot',
    storageBucket: 'michi-kahoot.firebasestorage.app',
    iosBundleId: 'com.example.miniKahootTeacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5a54hkzvPiIck4MPijeSKWS2pUB6Tiwc',
    appId: '1:925958524071:web:17f1aa72ab438e07bcdf82',
    messagingSenderId: '925958524071',
    projectId: 'michi-kahoot',
    authDomain: 'michi-kahoot.firebaseapp.com',
    storageBucket: 'michi-kahoot.firebasestorage.app',
  );
}
